### ISSUE TITLE
ImportError: No module named 'manager'

### ISSUE THREAD

**Issue by jmwoloso** [twoscoops/two-scoops-of-django-1.11#59]
Hello,

I'm new to django and I'm not sure if this error is a result of my project structure or something else. I'm using the same project structure recommended in Two Scoops, however when I attempt to use

```
python manage.py runserver
```
I get the following traceback:
```
Performing system checks...

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f4420e96400>
Traceback (most recent call last):
  File "/home/jwolosonovich/.virtualenvs/dashboards/lib/python3.4/site-packages/django/utils/autoreload.py", line 227, in wrapper
    fn(*args, **kwargs)
  File "/home/jwolosonovich/.virtualenvs/dashboards/lib/python3.4/site-packages/django/core/management/commands/runserver.py", line 125, in inner_run
    self.check(display_num_errors=True)
  File "/home/jwolosonovich/.virtualenvs/dashboards/lib/python3.4/site-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/jwolosonovich/.virtualenvs/dashboards/lib/python3.4/site-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/jwolosonovich/.virtualenvs/dashboards/lib/python3.4/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/jwolosonovich/.virtualenvs/dashboards/lib/python3.4/site-packages/django/core/checks/model_checks.py", line 30, in check_all_models
    errors.extend(model.check(**kwargs))
  File "/home/jwolosonovich/.virtualenvs/dashboards/lib/python3.4/site-packages/django/db/models/base.py", line 1282, in check
    errors.extend(cls._check_fields(**kwargs))
  File "/home/jwolosonovich/.virtualenvs/dashboards/lib/python3.4/site-packages/django/db/models/base.py", line 1357, in _check_fields
    errors.extend(field.check(**kwargs))
  File "/home/jwolosonovich/.virtualenvs/dashboards/lib/python3.4/site-packages/django/db/models/fields/__init__.py", line 909, in check
    errors = super(AutoField, self).check(**kwargs)
  File "/home/jwolosonovich/.virtualenvs/dashboards/lib/python3.4/site-packages/django/db/models/fields/__init__.py", line 219, in check
    errors.extend(self._check_backend_specific_checks(**kwargs))
  File "/home/jwolosonovich/.virtualenvs/dashboards/lib/python3.4/site-packages/django/db/models/fields/__init__.py", line 321, in _check_backend_specific_checks
    if router.allow_migrate(db, app_label, model_name=self.model._meta.model_name):
  File "/home/jwolosonovich/.virtualenvs/dashboards/lib/python3.4/site-packages/django/db/utils.py", line 293, in allow_migrate
    for router in self.routers:
  File "/home/jwolosonovich/.virtualenvs/dashboards/lib/python3.4/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/jwolosonovich/.virtualenvs/dashboards/lib/python3.4/site-packages/django/db/utils.py", line 251, in routers
    router = import_string(r)()
  File "/home/jwolosonovich/.virtualenvs/dashboards/lib/python3.4/site-packages/django/utils/module_loading.py", line 20, in import_string
    module = import_module(module_path)
  File "/home/jwolosonovich/.virtualenvs/dashboards/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2212, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2224, in _find_and_load_unlocked
ImportError: No module named 'manager'
```

Based on looking at the code within ```django/utils/module_loading.py``` it would seem that django might be using some sort of relative import and expecting to find a particular structure and when it can't find that structure, it fails. I didn't see anything referencing this in the book however, so I'm not sure if it is related to project structure or not.

Thanks in advance for any insight!

**Comment by natecox** [comment]
@jmwoloso can you post your project to a public project on github so we can see it directly? Seems like a possible configuration or virtualenv setup error. Hard to diagnose without code though.

**Comment by jmwoloso** [comment]
@natecox Hi, thanks for the reply. I was travelling, apologies for the late reply. I've made the repo public here:

https://github.com/jmwoloso/flex_dashboards

**Comment by pydanny** [comment]
If you use a Cookiecutter Django rendered template, do you have the same problems?

**Comment by jmwoloso** [comment]
Hi @pydanny 
I created a project using cookiecutter in the same repo root as the link above called `tesla_cc`. I get the following traceback when using `python manage.py runserver`:

```
Traceback (most recent call last):
  File "manage.py", line 29, in <module>
    execute_from_command_line(sys.argv)
  File "/home/jwolosonovich/.virtualenvs/dashboards/lib/python3.4/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/home/jwolosonovich/.virtualenvs/dashboards/lib/python3.4/site-packages/django/core/management/__init__.py", line 307, in execute
    settings.INSTALLED_APPS
  File "/home/jwolosonovich/.virtualenvs/dashboards/lib/python3.4/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/home/jwolosonovich/.virtualenvs/dashboards/lib/python3.4/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/jwolosonovich/.virtualenvs/dashboards/lib/python3.4/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/jwolosonovich/.virtualenvs/dashboards/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/jwolosonovich/jet_brains_projects/django_projects/flex_dashboards/tesla_cc/config/settings/local.py", line 12, in <module>
    from .base import *  # noqa
  File "/home/jwolosonovich/jet_brains_projects/django_projects/flex_dashboards/tesla_cc/config/settings/base.py", line 10, in <module>
    import environ
ImportError: No module named 'environ'
```

**Comment by jmwoloso** [comment]
@pydanny Actually, i think I was missing some requirements and I installed them, however I don't have Postgres installed, so running the server doesn't work for that reason, so not sure. I don't need Postgres for this project, but I'll install it this weekend and try again, then post updates here.

**Comment by pydanny** [comment]
Yup, missing requirements (and PostgreSQL) will cause problems.

In any case, this is a Cookiecutter Django problem, not an issue with Two Scoops of Django. Hence I'm closing it here as this is for issues with the book. If you need help with Cookiecutter Django, please use that [issue tracker](https://github.com/twoscoops/two-scoops-of-django-1.11/issues).

**Comment by jmwoloso** [comment]
sounds good, thank you all for your help!

**Comment by jmwoloso** [comment]
for anyone else that runs into this issue, I installed Postgres 9.6 and then my attempt to use `cookiecutter-django` to create the project structure was successful, so my recommendation is just to use that to accomplish the project structure in the book.
